kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:lts
    commands:
      - cd vue-block/
      - npm ci
      - npm run build

  - name: Commit
    image: appleboy/drone-git-push
    settings:
      remote: 'https://bitbucket.org/jcodigital/jcore-vue-broiler.git'
      commit: true
      commit_message: "[skip ci] Gutenberg block built by Drone CI"
